source 'https://rubygems.org'


gem 'breakpoint', '2.5.0' # 2.3.0
gem 'compass', '1.0.3' # 0.12.2
gem 'compass-core', '1.0.3' # 1.0.0.rc.1
gem 'compass-import-once',' 1.0.5'
gem 'compass-normalize', '1.5'
gem 'sass', '3.4.19'
gem 'sassy-maps', '0.4.0'
gem 'susy', '2.1.3' # 
gem 'toolkit', '2.6.0'
gem 'chunky_png', '1.3.5'